include:
  - docker-compose.svc.yml

services:
  caddy:
    image: caddy:2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./ui/build/:/srv/
    ports:
      - "80:80"

  alert:
    image: openreactor/alert
    build:
      context: .
      args:
        - SVC=alert
