name: Default
revision: "0"
auto:
    startOnApply: false
    startGas: false
vacuum:
    turboRotorSpeed: 90000
    turboRotorStartupHold: 15s
    lowVacuum: 0.01
    targetVacuum: 1e-05
    targetVacuumHold: 15s
cathode:
    tripCurrent: 8
    rampCurve: "0"
    voltageCutoff: 40
gas:
    flowRate: 10
    flowSlop: 0.1
    runtime: 1m0s
