name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22"

      - run: pip install --user pre-commit

      - name: Hash key for cache
        uses: seepine/hash-files@v1
        id: key-hash
        with:
          patterns: ".pre-commit-config.yaml"

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ steps.key-hash.outputs.hash }}

      - run: pre-commit run --all-files

      - run: go test -v ./...
